name: 'push'
on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_ACTOR: $GITHUB_ACTOR
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER
          echo GITHUB_SHA: $GITHUB_SHA
          echo GITHUB_REF: $GITHUB_REF
